export const SELECT_PLAYER_SYMBOL = 'SELECT_PLAYER_SYMBOL';
export const SELECT_AI_PLAYER_SYMBOL = 'SELECT_AI_PLAYER_SYMBOL';
export const SET_WINNER = 'SET_WINNER';
export const RELOAD_TEGAME = 'RELOAD_TEGAME';

export const SELECT_CELL = 'SELECT_CELL';
